### PR TITLE
[Feature] Add mobile-only Nav and Form icons to mobile-assets

### PR DESCRIPTION
**Pull request by narin**
## Description of Change

Adds the following icons which are mobile-only and therefore not added to the icon sprite sheet. Using same viewBox as icons extracted from vads sprite sheet and removed `fill` attributes.

Navigation
- description_outlined
- home_outlined
- medical_services_outlined
- request_quote_outlines

Form fields
- check_box_error
- check_box
- indeterminate_check_box
- radio_button_checked

Other
- circle
- crop_square

Removed all other icons as they have all been replaced by a material equivalent. Spreadsheet with full list of icons and their replacements here: https://docs.google.com/spreadsheets/d/15BqiZWwrhwl1BcGVu3-PCaCyz6ueI8VgHHlgpbvM2N4/edit#gid=840453829

#### Testing Packages

- 0.8.1-alpha.1

### Screenshots/Video

N/A

## Testing

- [x] Tested on Web

## PR Checklist
Code reviewer validation:
- General
	- [x] PR is linked to ticket(s)
	- [x] PR has `changelog` label applied if it's to be included in the changelog
	- [x] Acceptance criteria: 
		- All satisfied _or_
		- Documented reason for not being performed _or_
		- Split to separate ticket and ticket is linked by relevant AC(s)
	- [x] Above PR sections adequately filled out
	- [x] If any breaking changes, in accordance with the [pre-1.0.0 versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy): a CU ticket has been created for the VA Mobile App detailing necessary adjustments with the package version that will be published by this ticket
- Code
	- [x] Tests are included if appropriate (or split to separate ticket)
	- [x] New functions have proper TSDoc annotations

## Publish

If changes warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy) and the PR is approved and ready to merge:
- [ ] Merge `main` into branch
- [ ] Merge branch to `main`
- [ ] Verify that [Check Component Integrations](https://github.com/department-of-veterans-affairs/va-mobile-library/actions/workflows/check-component-integrations.yml) workflow ran successfully
- [ ] [Publish new version](https://github.com/department-of-veterans-affairs/va-mobile-library/actions/workflows/publish.yml) after merging

### CODE REVIEW

**Comment by jessicawoodin** [comment]
@narin Should `circle` or `crop_square` be included as well? Or will that be a separate PR?

**Comment by TimRoe** [comment]
Seconding Jessica's question on the `crop_square` which I assume is what we previously called `Bullet` since I think we had on our long term radar to bring VABulletList into the design system because React Native's default bullet lists use circles which goes against VA design language. Or put another way: future VA mobile apps would have utility in having that shared vs. living in the app and needing to clone it from flagship.

Not seconding her question on `circle` as currently the app doesn't use an icon at all for unread marking dots--it is just using RN to draw a circle by styling a view.

**Review by TimRoe — CHANGES_REQUESTED** [review]
Changes made look alright, but marking request changes for this late add AC:
> Remove any unneeded icons

Seems like we determined a lot of our icons should be removed--all except the new additions? Accordingly, should either link the spreadsheet or add a list to the PR of renames for record keeping of [old icon name] -> [new icon name].

**Comment by jessicawoodin** [comment]
> Seconding Jessica's question on the `crop_square` which I assume is what we previously called `Bullet` since I think we had on our long term radar to bring VABulletList into the design system because React Native's default bullet lists use circles which goes against VA design language. Or put another way: future VA mobile apps would have utility in having that shared vs. living in the app and needing to clone it from flagship.

Yes, `crop_square` is the new `bullet`. VA plans to transition to a standard circle bullet in the future, but for now, we need the square bullet.

> Not seconding her question on `circle` as currently the app doesn't use an icon at all for unread marking dots--it is just using RN to draw a circle by styling a view.

In the design files, we use an icon for the dot indicator, so that's why I suggested adding it. If it's not used in the app, we can remove it here and I'll also update the design files. If the app ever uses the dot indicator in another place in the app, we should consider adding the `circle` icon to ensure consistency across features.

**Comment by narin** [comment]
Added `circle` and `crop_square` icons and removed all of the old icons.

**Review by TimRoe — APPROVED** [review]
Looks good.

One lingering question: did we already have a ticket to consume the icons VADS is adding for us once they're published? If not, should probably make one to have a reminder to update the `assets` package and in turn the components once available.

**Comment by narin** [comment]
Stub ticket to add the icons we're waiting on from VADS here: #340

**Pull request merged**
