### PR TITLE
[Feature] Replace service emblems and VA SVGs with png. Add Space Force emblems.

### PR DESCRIPTION
**Pull request by narin**
## Description of Change

Replaces VA logo and service emblem SVGs with PNGs. Add Space Force emblems and VA logo with dark text.

#### Testing Packages

N/A

### Screenshots/Video

N/A (See images in [Files changed](https://github.com/department-of-veterans-affairs/va-mobile-library/pull/327/files))

## Testing

N/A

## PR Checklist
Code reviewer validation:
- General
	- [x] PR is linked to ticket(s)
	- [x] PR has `changelog` label applied if it's to be included in the changelog
	- [x] Acceptance criteria: 
		- All satisfied _or_
		- Documented reason for not being performed _or_
		- Split to separate ticket and ticket is linked by relevant AC(s)
	- [x] Above PR sections adequately filled out
	- [x] If any breaking changes, in accordance with the [pre-1.0.0 versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy): a CU ticket has been created for the VA Mobile App detailing necessary adjustments with the package version that will be published by this ticket
- Code
	- [x] Tests are included if appropriate (or split to separate ticket)
	- [x] New functions have proper TSDoc annotations

## Publish

If changes warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy) and the PR is approved and ready to merge:
- [ ] Merge `main` into branch
- [ ] Merge branch to `main`
- [ ] Verify that [Check Component Integrations](https://github.com/department-of-veterans-affairs/va-mobile-library/actions/workflows/check-component-integrations.yml) workflow ran successfully
- [ ] [Publish new version](https://github.com/department-of-veterans-affairs/va-mobile-library/actions/workflows/publish.yml) after merging

### CODE REVIEW

**Review by TimRoe — CHANGES_REQUESTED** [review]
Not sure where exactly we pulled the PNGs for existing service emblems from, but:
- Definitely need to update:
   - Army - the yellow bands are crazy thick compared to what they're supposed to be, throwing off proportions
   - Marines - The wrap-around chain on the anchor and lines on the globe appear to be MS Paint-ed on
- Should probably update:
   - Coast Guard - Missing transparency in the loops of the anchors which'll stand out and look weird on a blue background
   - Navy - Incorrect outer rope detail w/ dark brown, rope/bars on the anchor are way too dark, and the chain too flat
- Nitpicky update we could maybe leave alone:
   - Air Force -  the winged trident part is off center (touching the top of the shield) and doesn't have the reddish tips on the tridents

At a minimum, we should probably just [copy VA.gov's PNGs](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/site/assets/img) (note: most of these are also slightly off, but less so). Preferably we should probably make them [from sources I'd documented](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5878#issuecomment-1581165124) when initially noting issues with the jump to SVGs. Glancing through my post there, I think we can pull:
- Army, Air Force, and maybe Marines (not good, but neither is their public material) from [here](https://www.defense.gov/Resources/Branding-and-Trademarks/DOD-Trademark-Licensing-Guide/#one)
- Navy from [here](https://media.defense.gov/2021/Apr/08/2002616384/-1/-1/1/FINALLICENSINGGUIDELINES_DIGITAL_2162021.PDF) (page 13)
- Coast guard from [here](https://media.defense.gov/2021/Oct/20/2002877103/-1/-1/1/USCG%20BRANDING%20GUIDELINES%20&%20FAQS.PDF) (page 3)

With design help adding transparency (with the latter 2 at least).

**Comment by TimRoe** [comment]
> For some reason, the app currently uses different emblems than VADS

The reason is because a React Native update broke using the PNG-as-SVG method being used for the service emblems, it had already been merged to develop, and backing out such a change would've been a big pain so SVG versions were found and swapped in. It was only much later realized that the VA Logo was still using PNG-as-SVG so maybe they could've been adjusted to continue working. 

> Currently, the files that are used in the app are not scaling properly when converted to PNG and exported at various sizes.

Not sure I follow this--since they're SVGs, they should scale fine (and [looking at them in storybook](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/story/icon--preloaded&args=width:550;height:550;name:MarineCorps) seem to).

**Comment by jessicawoodin** [comment]
Going forward, the mobile library should provide the same emblems that VADS provides. I updated the Emblems.zip file in the ticket. The zip file also includes the two new Space Force logos. I will let VADS know about the two additional logos and also see if they might have higher quality files for all emblems.

**Comment by TimRoe** [comment]
> Going forward, the mobile library should provide the same emblems that VADS provides. I updated the Emblems.zip file in the ticket. The zip file also includes the two new Space Force logos. I will let VADS know about the two additional logos and also see if they might have higher quality files for all emblems.

For clarity, VADS currently doesn't have the emblems at all. They are part of the [VA.gov repo]([vets-website](https://github.com/department-of-veterans-affairs/vets-website/tree/main)).

There is [an outstanding ticket for VADS](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2214) to incorporate them separately. Potentially that ticket could also serve for tracking getting higher quality versions (potentially SVGs of all reasonable sizes that can scale for website, mobile, whatever).

**Pull request merged**
